# Generated by Django 5.1.4 on 2024-12-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List current medications and dosages'),
        ),
    ]
